[package]
name = "chass"
version = "0.1.0"
authors = ["Abhinav Tushar <abhinav@lepisma.xyz>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
clap = "~2.33"
prettytable-rs = "^0.8"